macro(configure_fortran_default_r8)
  if (CMAKE_Fortran_COMPILER_ID STREQUAL "GNU")
    string(APPEND CMAKE_Fortran_FLAGS " -fdefault-real-8 -fdefault-double-8")
  elseif(CMAKE_Fortran_COMPILER_ID STREQUAL "Intel")
    string(APPEND CMAKE_Fortran_FLAGS " -r8")
  elseif(CMAKE_Fortran_COMPILER_ID STREQUAL "IntelLLVM")
    string(APPEND CMAKE_Fortran_FLAGS " -r8")
  endif()
  ## Define installation directory form
  #set(CMAKE_Fortran_MODULE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/modules)
endmacro()